// NetInfo
export const NETINFO_SET_STATUS = 'NETINFO_SET_STATUS';
// photoPicker
export const GET_PHOTO = 'GET_PHOTO';
export const CLEAR_PHOTO = 'CLEAR_PHOTO';
export const CLEAR_ALL_PHOTOS = 'CLEAR_ALL_PHOTOS';
export const SET_NAME_PATIENT = 'SET_NAME_PATIENT';
export const SET_COMMENT_PATIENT = 'SET_COMMENT_PATIENT';
// settings
export const SET_VALIDATE_EMAIL = 'SET_VALIDATE_EMAIL';
export const SET_NAME_PRACTICE = 'SET_NAME_PRACTICE';
export const SET_LOCATION_PRACTICE = 'SET_LOCATION_PRACTICE';
export const SET_EMAIL_PRACTICE = 'SET_EMAIL_PRACTICE';
export const GET_IMAGES_BY_EMAIL = 'GET_IMAGES_BY_EMAIL';
export const SAVE_IMAGES_ON_DEVICE = 'SAVE_IMAGES_ON_DEVICE';